name: flutter_shopping_cart
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

